/******************************************************************************
* File Name:   main.c
*
* Description: This is the source code for the XMC MCU: ERU external interrupt example
*              for ModusToolbox.
*              External signal is fed to Event Request Unit (ERU) using one of the GPIO pins.
*              Service request interrupt is generated based on the falling edge of the external signal.
*              LED is toggled at every falling edge of the external signal inside the ERU service request interrupt.
*
* Related Document: See README.md
*
******************************************************************************
*
* Copyright (c) 2015-2022, Infineon Technologies AG
* All rights reserved.
*
* Boost Software License - Version 1.0 - August 17th, 2003
*
* Permission is hereby granted, free of charge, to any person or organization
* obtaining a copy of the software and accompanying documentation covered by
* this license (the "Software") to use, reproduce, display, distribute,
* execute, and transmit the Software, and to prepare derivative works of the
* Software, and to permit third-parties to whom the Software is furnished to
* do so, all subject to the following:
*
* The copyright notices in the Software and this entire statement, including
* the above license grant, this restriction and the following disclaimer,
* must be included in all copies of the Software, in whole or in part, and
* all derivative works of the Software, unless such copies or derivative
* works are solely in the form of machine-executable object code generated by
* a source language processor.
*
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
* IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
* FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
* SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
* FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
* ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
* DEALINGS IN THE SOFTWARE.
*
*****************************************************************************/

#include <stdio.h>
#include "cybsp.h"
#include "cy_utils.h"
#include "cy_retarget_io.h"

/*******************************************************************************
* Defines
*******************************************************************************/

/* Define macro to enable/disable printing of debug messages */
#define ENABLE_XMC_DEBUG_PRINT              (0)

/* Define macro to set the loop count before printing debug messages */
#if ENABLE_XMC_DEBUG_PRINT
#define DEBUG_LOOP_COUNT_MAX                (1U)
#endif

#if (UC_SERIES == XMC13) || (UC_SERIES == XMC12) || (UC_SERIES == XMC11) 
#define INTERRUPT_PRIORITY_NODE_ID          eru_0_ogu_0_IRQN
#define INTERRUPT_EVENT_PRIORITY            eru_0_ogu_0_NUM
#define ERU_EXTERNAL_EVENT_HANDLER          eru_0_ogu_0_INTERRUPT_HANDLER
#endif

#if (UC_SERIES == XMC14)
#define INTERRUPT_PRIORITY_NODE_ID          IRQ3_IRQn
#define INTERRUPT_EVENT_PRIORITY            (3U)
#define ERU_EXTERNAL_EVENT_HANDLER          IRQ_Hdlr_3
#endif

#if (UC_SERIES == XMC48) || (UC_SERIES == XMC47) ||(UC_SERIES == XMC45) || (UC_SERIES == XMC44) || (UC_SERIES == XMC42)
#define INTERRUPT_PRIORITY_NODE_ID          eru_1_ogu_0_IRQN
#define INTERRUPT_EVENT_PRIORITY            eru_1_ogu_0_NUM
#define ERU_EXTERNAL_EVENT_HANDLER          eru_1_ogu_0_INTERRUPT_HANDLER
#endif

#if (UC_SERIES == XMC43)
#define INTERRUPT_PRIORITY_NODE_ID          ERU0_0_IRQn
#define INTERRUPT_EVENT_PRIORITY            (63U)
#define ERU_EXTERNAL_EVENT_HANDLER          IRQ_Hdlr_1
#endif

/* Define and initialize the interrupt event count to zero */
static volatile uint32_t interrupt_event_count = 0;

/*******************************************************************************
* Function Name: ERU_EXTERNAL_EVENT_HANDLER
********************************************************************************
* Summary:
* This is the interrupt handler function for the ERU external interrupt.
*
* Parameters:
*  none
*
* Return:
*  void
*
*******************************************************************************/
void ERU_EXTERNAL_EVENT_HANDLER(void)
{
    /*Toggle the LED*/
    XMC_GPIO_ToggleOutput(CYBSP_USER_LED_PORT, CYBSP_USER_LED_PIN);
    interrupt_event_count++;
}

/*******************************************************************************
* Function Name: main
********************************************************************************
* Summary:
* This is the main function.
*  1. It demonstrates the usage of the Event Request Unit(ERU).
*  2. ERU consists of Event Trigger logic (ETL), which is configured to trigger an event during the falling edge of an external signal.
*  3. Trigger output from ETL is directed to one of the Output Gating Unit (OGU), which is configured to generate a service request.
*  4. For every falling edge of the external signal, LED is toggled inside the interrupt service request.
*
* Parameters:
*  none
*
* Return:
*  int
*
*******************************************************************************/

int main(void)
{
    cy_rslt_t result;

    #if ENABLE_XMC_DEBUG_PRINT
    /* Assign false to disable printing of debug messages*/
    static volatile bool debug_printf = true;
    #endif

    /* Initialize the device and board peripherals */
    result = cybsp_init();
    if (result != CY_RSLT_SUCCESS)
    {
        CY_ASSERT(0);
    }

    /* Initialize retarget-io to use the debug UART port */
    cy_retarget_io_init(CYBSP_DEBUG_UART_HW);

    #if ENABLE_XMC_DEBUG_PRINT
    printf("Initialization done\r\n");
    #endif

    #if (UC_SERIES == XMC14) || (UC_SERIES == XMC13) || (UC_SERIES == XMC12) ||(UC_SERIES == XMC11)
    /*Set Priority for IRQ*/
    NVIC_SetPriority(INTERRUPT_PRIORITY_NODE_ID,INTERRUPT_EVENT_PRIORITY);
    #endif

    #if (UC_SERIES == XMC48) || (UC_SERIES == XMC47) ||(UC_SERIES == XMC45) || (UC_SERIES == XMC44) || (UC_SERIES == XMC43) || (UC_SERIES == XMC42)
    /*Set Priority for IRQ*/
    NVIC_SetPriority(INTERRUPT_PRIORITY_NODE_ID,NVIC_EncodePriority(NVIC_GetPriorityGrouping(),INTERRUPT_EVENT_PRIORITY, 0));
    #endif

    /*Enable the Interrupt*/
    NVIC_EnableIRQ(INTERRUPT_PRIORITY_NODE_ID);

    /*Infinite loop */
    while(1)
    {
        #if ENABLE_XMC_DEBUG_PRINT
        if(debug_printf && (interrupt_event_count == DEBUG_LOOP_COUNT_MAX))
        {
            debug_printf = false;
            /* Print message after the loop has run DEBUG_LOOP_COUNT_MAX times */
            printf("LED is toggled inside the interrupt service request, for every falling edge of the external signal\r\n");
        }
        #endif
    }
}

/* [] END OF FILE */
